### ISSUE TITLE
Create some helper class

### ISSUE THREAD

**Issue by ghost** [hivelocityinc/adminize#24]
## Display

``` css
.display--block {
    display: block;
}
```
## Vertical Align

``` css
.valign--middle {
    vertical-align: middle;
}
```
